"""Initialisation des tables

Revision ID: 8a70cbb82fa8
Revises: 
Create Date: 2025-07-13 11:09:11.347703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a70cbb82fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membre')
    op.drop_table('user')
    op.drop_table('paiement')
    op.drop_table('engagement')
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('groupe', sa.String(length=50), nullable=True))
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('groupe')
        batch_op.drop_column('photo')

    op.create_table('engagement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('membre_id', sa.INTEGER(), nullable=False),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.Column('date_engagement', sa.DATETIME(), nullable=True),
    sa.Column('date_limite', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('membre_id', sa.INTEGER(), nullable=False),
    sa.Column('engagement_id', sa.INTEGER(), nullable=False),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.Column('date_paiement', sa.DATETIME(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=50), nullable=True),
    sa.Column('enregistre_par', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.ForeignKeyConstraint(['enregistre_par'], ['user.id'], ),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('membre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('engagement_total', sa.FLOAT(), nullable=False),
    sa.Column('montant_paye', sa.FLOAT(), nullable=True),
    sa.Column('date_limite', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
